version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - BACKEND_DB_PATH=/data/state.db
    volumes:
      - backend_data:/data
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8085:80"  # host:container
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
